# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cd59289fb0a02385762d9fe75ea8eaf3ca3359b8182231c1571d1d2d7bf39e7f48af1d61716a613c778c10916ec34daf131dcb72262d065e2e2ba9095659dde

test:
  secret_key_base: 46036a64bf1fad08c005d91ef4e0b8a3334d8a02ad2bcb675d7099329fe0f5bc259fe12a6ccba1f6bd9ea30e8df0a9aba59a1e9f70c01cbb7662e50d7cc11af0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
